spring.application.name=backend

# H2
spring.datasource.url=jdbc:h2:mem:tododb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# h
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=todoTaskSecretKeyForJwtSigningMustBeLongEnough12345
jwt.expiration=86400000